pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Setup Environment') {
            steps {
                sh 'python3 -m venv $VENV'
                sh './$VENV/bin/pip install --upgrade pip'
                sh './$VENV/bin/pip install -r requirements.txt'
            }
        }

        stage('Train Model') {
            steps {
                sh './$VENV/bin/python src/train.py'
            }
        }

        stage('Evaluate and Register') {
            steps {
                sh './$VENV/bin/python src/evaluate.py'
            }
        }

        stage('Deploy Model API') {
            steps {
                dir('serve') {
                    sh 'docker build -t iris-model-api .'
                    sh 'docker run -d -p 7001:7001 iris-model-api || echo "Container already running"'
                }
            }
        }
    }
}
